version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fundyze-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - BACKEND_HOST=${BACKEND_HOST:-0.0.0.0}
      - BACKEND_PORT=8080
      - RUST_ENV=${RUST_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - fundyze-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    container_name: fundyze-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - fundyze-network

networks:
  fundyze-network:
    driver: bridge
